/**
 * Seed all 28 Indian states + 8 UTs with theme colors.
 * Run: node src/seed/states.js
 */
require("dotenv").config();
const { sequelize, State } = require("../models");

const states = [
  { name: "Andhra Pradesh",       code: "AP",  theme: { primary: "#1e6f5c", secondary: "#e8c547", bg: "#f5f1e8" }, symbol: { animal: "Blackbuck", bird: "Indian Roller", flower: "Water Lily", tree: "Neem", emoji: "🦌" }, languages: [{code:"te",name:"Telugu",native:"తెలుగు",default:true},{code:"ur",name:"Urdu",native:"اردو"},{code:"en",name:"English",native:"English"}] },
  { name: "Arunachal Pradesh",    code: "AR",  theme: { primary: "#2d6a4f", secondary: "#d4a276", bg: "#faf7f2" }, symbol: { animal: "Mithun", bird: "Great Hornbill", flower: "Foxtail Orchid", tree: "Hollong", emoji: "🦏" }, languages: [{code:"en",name:"English",native:"English",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"}] },
  { name: "Assam",                code: "AS",  theme: { primary: "#6b4226", secondary: "#e6c229", bg: "#fff8e7" }, symbol: { animal: "Indian Rhinoceros", bird: "White-winged Duck", flower: "Foxtail Orchid", tree: "Hollong", emoji: "🦏" }, languages: [{code:"as",name:"Assamese",native:"অসমীয়া",default:true},{code:"bn",name:"Bengali",native:"বাংলা"},{code:"en",name:"English",native:"English"}] },
  { name: "Bihar",                code: "BR",  theme: { primary: "#b5651d", secondary: "#4a7c59", bg: "#fdf6ec" }, symbol: { animal: "Gaur", bird: "Indian Roller", flower: "Kachnar", tree: "Peepal", emoji: "🐃" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"ur",name:"Urdu",native:"اردو"},{code:"en",name:"English",native:"English"}] },
  { name: "Chhattisgarh",         code: "CG",  theme: { primary: "#2e7d32", secondary: "#ff8f00", bg: "#f1f8e9" }, symbol: { animal: "Wild Buffalo", bird: "Hill Myna", flower: "Rhynchostylis Orchid", tree: "Sal", emoji: "🐃" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"cg",name:"Chhattisgarhi",native:"छत्तीसगढ़ी"},{code:"en",name:"English",native:"English"}] },
  { name: "Goa",                  code: "GA",  theme: { primary: "#00838f", secondary: "#f9a825", bg: "#e0f7fa" }, symbol: { animal: "Gaur", bird: "Ruby-throated Yellow Bulbul", flower: "Plumeria", tree: "Matti", emoji: "🌺" }, languages: [{code:"kok",name:"Konkani",native:"कोंकणी",default:true},{code:"mr",name:"Marathi",native:"मराठी"},{code:"en",name:"English",native:"English"}] },
  { name: "Gujarat",              code: "GJ",  theme: { primary: "#c62828", secondary: "#fbc02d", bg: "#fff3e0" }, symbol: { animal: "Asiatic Lion", bird: "Greater Flamingo", flower: "Marigold", tree: "Mango", emoji: "🦁" }, languages: [{code:"gu",name:"Gujarati",native:"ગુજરાતી",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Haryana",              code: "HR",  theme: { primary: "#1565c0", secondary: "#43a047", bg: "#e3f2fd" }, symbol: { animal: "Blackbuck", bird: "Black Francolin", flower: "Lotus", tree: "Peepal", emoji: "🦌" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"pa",name:"Punjabi",native:"ਪੰਜਾਬੀ"},{code:"en",name:"English",native:"English"}] },
  { name: "Himachal Pradesh",     code: "HP",  theme: { primary: "#283593", secondary: "#66bb6a", bg: "#e8eaf6" }, symbol: { animal: "Snow Leopard", bird: "Western Tragopan", flower: "Pink Rhododendron", tree: "Deodar Cedar", emoji: "🐆" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Jharkhand",            code: "JH",  theme: { primary: "#4e342e", secondary: "#7cb342", bg: "#efebe9" }, symbol: { animal: "Asian Elephant", bird: "Asian Koel", flower: "Palash", tree: "Sal", emoji: "🐘" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"sat",name:"Santali",native:"ᱥᱟᱱᱛᱟᱲᱤ"},{code:"en",name:"English",native:"English"}] },
  { name: "Karnataka",            code: "KA",  theme: { primary: "#ad1457", secondary: "#fdd835", bg: "#fce4ec" }, symbol: { animal: "Asian Elephant", bird: "Indian Roller", flower: "Lotus", tree: "Sandalwood", emoji: "🐘" }, languages: [{code:"kn",name:"Kannada",native:"ಕನ್ನಡ",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Kerala",               code: "KL",  theme: { primary: "#00695c", secondary: "#ffb300", bg: "#e0f2f1" }, symbol: { animal: "Indian Elephant", bird: "Great Hornbill", flower: "Golden Shower", tree: "Coconut", emoji: "🐘" }, languages: [{code:"ml",name:"Malayalam",native:"മലയാളം",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Madhya Pradesh",       code: "MP",  theme: { primary: "#2e7d32", secondary: "#ff6f00", bg: "#f1f8e9" }, symbol: { animal: "Barasingha", bird: "Indian Paradise Flycatcher", flower: "White Lily", tree: "Banyan", emoji: "🦌" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Maharashtra",          code: "MH",  theme: { primary: "#e65100", secondary: "#1b5e20", bg: "#fff3e0" }, symbol: { animal: "Indian Giant Squirrel", bird: "Yellow-footed Green Pigeon", flower: "Jarul", tree: "Mango", emoji: "🐿️" }, languages: [{code:"mr",name:"Marathi",native:"मराठी",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Manipur",              code: "MN",  theme: { primary: "#4527a0", secondary: "#e65100", bg: "#ede7f6" }, symbol: { animal: "Sangai Deer", bird: "Mrs. Hume's Pheasant", flower: "Shirui Lily", tree: "Uningthou", emoji: "🦌" }, languages: [{code:"mni",name:"Meiteilon",native:"মৈতৈলোন্",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Meghalaya",            code: "ML",  theme: { primary: "#1b5e20", secondary: "#fbc02d", bg: "#e8f5e9" }, symbol: { animal: "Clouded Leopard", bird: "Hill Myna", flower: "Lady's Slipper Orchid", tree: "Gamari", emoji: "🐆" }, languages: [{code:"en",name:"English",native:"English",default:true},{code:"kha",name:"Khasi",native:"Khasi"},{code:"grt",name:"Garo",native:"Garo"}] },
  { name: "Mizoram",              code: "MZ",  theme: { primary: "#0277bd", secondary: "#ef6c00", bg: "#e1f5fe" }, symbol: { animal: "Seram's Muntjac", bird: "Mrs. Hume's Pheasant", flower: "Red Vanda", tree: "Ironwood", emoji: "🦌" }, languages: [{code:"lus",name:"Mizo",native:"Mizo ṭawng",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Nagaland",             code: "NL",  theme: { primary: "#33691e", secondary: "#d84315", bg: "#f1f8e9" }, symbol: { animal: "Mithun", bird: "Blyth's Tragopan", flower: "Rhododendron", tree: "Alder", emoji: "🐃" }, languages: [{code:"en",name:"English",native:"English",default:true}] },
  { name: "Odisha",               code: "OD",  theme: { primary: "#bf360c", secondary: "#0097a7", bg: "#fbe9e7" }, symbol: { animal: "Sambar Deer", bird: "Indian Roller", flower: "Ashoka", tree: "Sacred Fig", emoji: "🦌" }, languages: [{code:"or",name:"Odia",native:"ଓଡ଼ିଆ",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Punjab",               code: "PB",  theme: { primary: "#e65100", secondary: "#1565c0", bg: "#fff3e0" }, symbol: { animal: "Blackbuck", bird: "Northern Goshawk", flower: "Gladiolus", tree: "Shisham", emoji: "🦌" }, languages: [{code:"pa",name:"Punjabi",native:"ਪੰਜਾਬੀ",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Rajasthan",            code: "RJ",  theme: { primary: "#b71c1c", secondary: "#f9a825", bg: "#fce4ec" }, symbol: { animal: "Chinkara", bird: "Great Indian Bustard", flower: "Rohida", tree: "Khejri", emoji: "🦌" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"raj",name:"Rajasthani",native:"राजस्थानी"},{code:"en",name:"English",native:"English"}] },
  { name: "Sikkim",               code: "SK",  theme: { primary: "#00838f", secondary: "#ff8f00", bg: "#e0f7fa" }, symbol: { animal: "Red Panda", bird: "Blood Pheasant", flower: "Noble Dendrobium", tree: "Rhododendron", emoji: "🐾" }, languages: [{code:"ne",name:"Nepali",native:"नेपाली",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Tamil Nadu",           code: "TN",  theme: { primary: "#880e4f", secondary: "#fdd835", bg: "#fce4ec" }, symbol: { animal: "Nilgiri Tahr", bird: "Emerald Dove", flower: "Gloriosa Lily", tree: "Palmyra Palm", emoji: "🐐" }, languages: [{code:"ta",name:"Tamil",native:"தமிழ்",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Telangana",            code: "TS",  theme: { primary: "#1a237e", secondary: "#ffab00", bg: "#e8eaf6" }, symbol: { animal: "Jinka (Deer)", bird: "Indian Roller", flower: "Tangedu", tree: "Jammi Chettu", emoji: "🦌" }, languages: [{code:"te",name:"Telugu",native:"తెలుగు",default:true},{code:"ur",name:"Urdu",native:"اردو"},{code:"en",name:"English",native:"English"}] },
  { name: "Tripura",              code: "TR",  theme: { primary: "#4a148c", secondary: "#00c853", bg: "#f3e5f5" }, symbol: { animal: "Phayre's Langur", bird: "Green Imperial Pigeon", flower: "Nageshwar", tree: "Agar", emoji: "🐒" }, languages: [{code:"bn",name:"Bengali",native:"বাংলা",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Uttar Pradesh",        code: "UP",  theme: { primary: "#0d47a1", secondary: "#e65100", bg: "#e3f2fd" }, symbol: { animal: "Barasingha", bird: "Sarus Crane", flower: "Palash", tree: "Ashoka", emoji: "🦌" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"ur",name:"Urdu",native:"اردو"},{code:"en",name:"English",native:"English"}] },
  { name: "Uttarakhand",          code: "UK",  theme: { primary: "#1b5e20", secondary: "#01579b", bg: "#e8f5e9" }, symbol: { animal: "Alpine Musk Deer", bird: "Himalayan Monal", flower: "Brahma Kamal", tree: "Buransh", emoji: "🦌" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"sa",name:"Sanskrit",native:"संस्कृतम्"},{code:"en",name:"English",native:"English"}] },
  { name: "West Bengal",          code: "WB",  theme: { primary: "#311b92", secondary: "#f57f17", bg: "#ede7f6" }, symbol: { animal: "Fishing Cat", bird: "White-breasted Kingfisher", flower: "Night-flowering Jasmine", tree: "Chatim", emoji: "🐱" }, languages: [{code:"bn",name:"Bengali",native:"বাংলা",default:true},{code:"ne",name:"Nepali",native:"नेपाली"},{code:"en",name:"English",native:"English"}] },
  // Union Territories
  { name: "Andaman & Nicobar",    code: "AN",  theme: { primary: "#006064", secondary: "#ff6d00", bg: "#e0f7fa" }, symbol: { animal: "Dugong", bird: "Andaman Woodpecker", flower: "Andaman Redwood", tree: "Andaman Padauk", emoji: "🐋" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Chandigarh",           code: "CH",  theme: { primary: "#37474f", secondary: "#ffab00", bg: "#eceff1" }, symbol: { animal: "Indian Grey Mongoose", bird: "Indian Grey Hornbill", flower: "Dhak", tree: "Mango", emoji: "🏛️" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"pa",name:"Punjabi",native:"ਪੰਜਾਬੀ"},{code:"en",name:"English",native:"English"}] },
  { name: "Dadra Nagar Haveli & Daman Diu", code: "DD", theme: { primary: "#004d40", secondary: "#ff8f00", bg: "#e0f2f1" }, symbol: { emoji: "🏝️" }, languages: [{code:"gu",name:"Gujarati",native:"ગુજરાતી",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Delhi",                code: "DL",  theme: { primary: "#b71c1c", secondary: "#1565c0", bg: "#ffebee" }, symbol: { animal: "Nilgai", bird: "House Sparrow", flower: "Alfalfa", emoji: "🏛️" }, languages: [{code:"hi",name:"Hindi",native:"हिन्दी",default:true},{code:"ur",name:"Urdu",native:"اردو"},{code:"pa",name:"Punjabi",native:"ਪੰਜਾਬੀ"},{code:"en",name:"English",native:"English"}] },
  { name: "Jammu & Kashmir",      code: "JK",  theme: { primary: "#1a237e", secondary: "#2e7d32", bg: "#e8eaf6" }, symbol: { animal: "Hangul (Kashmir Stag)", bird: "Black-necked Crane", flower: "Lotus", tree: "Chinar", emoji: "🦌" }, languages: [{code:"ks",name:"Kashmiri",native:"کٲشُر",default:true},{code:"doi",name:"Dogri",native:"डोगरी"},{code:"ur",name:"Urdu",native:"اردو"},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Ladakh",               code: "LA",  theme: { primary: "#283593", secondary: "#ff8f00", bg: "#e8eaf6" }, symbol: { animal: "Snow Leopard", bird: "Black-necked Crane", emoji: "🐆" }, languages: [{code:"lad",name:"Ladakhi",native:"ལ་དྭགས་སྐད",default:true},{code:"hi",name:"Hindi",native:"हिन्दी"},{code:"en",name:"English",native:"English"}] },
  { name: "Lakshadweep",          code: "LD",  theme: { primary: "#01579b", secondary: "#00c853", bg: "#e1f5fe" }, symbol: { animal: "Butterfly Fish", bird: "Sooty Tern", tree: "Breadfruit", emoji: "🐠" }, languages: [{code:"ml",name:"Malayalam",native:"മലയാളം",default:true},{code:"en",name:"English",native:"English"}] },
  { name: "Puducherry",           code: "PY",  theme: { primary: "#880e4f", secondary: "#00838f", bg: "#fce4ec" }, symbol: { bird: "Asian Koel", flower: "Cannon Ball Flower", tree: "Bael", emoji: "🌸" }, languages: [{code:"ta",name:"Tamil",native:"தமிழ்",default:true},{code:"fr",name:"French",native:"Français"},{code:"en",name:"English",native:"English"}] },
];

async function seed() {
  try {
    await sequelize.sync({ alter: true });
    for (const s of states) {
      await State.upsert(s);
    }
    console.log(`✅ Seeded ${states.length} states/UTs`);
    process.exit(0);
  } catch (err) {
    console.error("Seed failed:", err);
    process.exit(1);
  }
}

seed();
